name: EliteSkyProva1
version: '${project.version}'
main: org.itzabu.eliteskyprova1.EliteSkyProva1
api-version: '1.20'
author: ItzAbu
commands:
  reload:
    description: Reload the plugin
    usage: /<command>
  Axes:
    description: Give the player an axe
    usage: /<command>
    aliases: [axe]
  AxeSave:
    description: Save the axe
    usage: /<command>
    aliases: [axesave]



