name: EliteSkyProva1
version: '1.0-SNAPSHOT'
main: org.itzabu.eliteskyprova1.EliteSkyProva1
api-version: '1.20'
author: ItzAbu
commands:
  reload:
    description: Reload the plugin
    usage: /<command>



